baseURL = "https://jmwinemiller.github.io/"
languageCode = "en-us"
title = "Jordan Winemiller"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLangauge = "en"
SectionPageMenu = "main"
Pageinate = 3
googleAnalytics = ""
enableRobotsTXT = true

[langauges]
  [langauges.en]
    title = "Ananke"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Jordan Winemiller"
  favicon = ""
  site_logo = ""
  description = "Personal data science and statistics portfolio site."
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/jmwinemiller"